name: Subscribe to Issues and PRs using GraphQL

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  subscribe:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check issues and PRs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/scripts/subscribe_to_issues_and_prs_graphql.py
